#!/bin/sh

./autogen.sh
./my-configure mingw
make clean
make -j4
cp src/froxcomposband.exe .
if [ -n "$1" ]
then
    file=froxcomposband-"$1".zip
else
    file=froxcomposband-"$(git describe)".zip
fi

rm $file
find ./lib -name Makefile -prune -o -name .deps -prune -o -print | zip $file -@
zip $file froxcomposband.exe README.md
